# Generated by Django 4.2.3 on 2023-07-21 15:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='google code', max_length=200, null=True)),
                ('code_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('article_status', models.CharField(blank=True, choices=[('publish', 'publish'), ('draft', 'draft')], max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('lead_img', models.ImageField(blank=True, null=True, upload_to='media_files/blog')),
                ('lead_img_alt', models.CharField(blank=True, help_text='alt text of an image', max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('summary', models.TextField(blank=True, help_text='31 letters max will give a better out look', null=True)),
                ('author', models.CharField(blank=True, default='wmecreatives', max_length=200, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='media_files/authorImg')),
                ('author_image_atlt_text', models.CharField(blank=True, help_text='alt text of an image', max_length=1000, null=True)),
                ('youtube_video_link', models.TextField(blank=True, null=True)),
                ('num_views', models.CharField(blank=True, max_length=30, null=True)),
                ('read_time', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media_files/Categories/icon')),
                ('icon_class', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='article image', max_length=300, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='api image', max_length=200, null=True)),
                ('uploded', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photographer', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='api_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.categories'),
        ),
    ]
