# Generated by Django 4.2.3 on 2023-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categories_is_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='num_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
