# Generated by Django 4.2.3 on 2023-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_num_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='author',
            field=models.CharField(blank=True, default='wmecreatives', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='lead_img',
            field=models.ImageField(blank=True, null=True, upload_to='media_files/blog'),
        ),
        migrations.AddField(
            model_name='categories',
            name='lead_img_alt',
            field=models.CharField(blank=True, help_text='alt text of an image', max_length=1000, null=True),
        ),
    ]
