# Generated by Django 4.2.3 on 2023-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categories_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
